global_frame: odom

rolling_window: true
publish_frequency: 2.0

# size of costmap is specified in robot folder

# plugins for local costmap are in robot folder
plugins:
 - {name: obstacles, type: "costmap_2d::FetchDepthLayer"}
 - {name: inflater,  type: "costmap_2d::InflationLayer", inflation_radius: 0.1}
