width: 4.0
height: 4.0
resolution: 0.025

plugins:
 - {name: obstacles, type: "costmap_2d::FetchDepthLayer"}
 - {name: inflater,  type: "costmap_2d::InflationLayer", inflation_radius: 0.1}

obstacles:
  publish_observations: false
